workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild -version
          xcodebuild -project DottedCalendar.xcodeproj -scheme DottedCalendar -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/**/*.app
