workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: Build iOS app (simulator, no signing)
        script: |
          xcodebuild -scheme DottedCalendar \
            -configuration Release \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            build

    artifacts:
      - build/Build/Products/Release-iphonesimulator/*.app
